### ISSUE TITLE
Loading dataframe containing time info through Orange

### ISSUE THREAD

**Issue by vpejovic** [biolab/monroe-anal#3]
While loading data (dataframe attached in a zip file) through iPython Connector in Orange I got the following error:
```
Traceback (most recent call last):
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/Orange/data/variable.py", line 996, in parse
    value = float(datestr)
ValueError: could not convert string to float: '2018-02-27 00:02:47.952189+00:00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/ricercando/orange_widgets/owipythonconnector.py", line 127, in on_file_changed
    self.output()
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/ricercando/orange_widgets/owipythonconnector.py", line 134, in output
    if isinstance(output_obj, type)), None)
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/ricercando/orange_widgets/owipythonconnector.py", line 134, in <genexpr>
    if isinstance(output_obj, type)), None)
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/ricercando/orange_widgets/util.py", line 50, in table_from_frame
    X.append(s.astype('str').replace('NaT', np.nan).map(tvar.parse).values)
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/pandas/core/series.py", line 2158, in map
    new_values = map_f(values, arg)
  File "pandas/_libs/src/inference.pyx", line 1574, in pandas._libs.lib.map_infer (pandas/_libs/lib.c:66652)
  File "/Users/veljko/.virtualenvs/ricercando3/lib/python3.6/site-packages/Orange/data/variable.py", line 1000, in parse
    raise ERROR
ValueError: Invalid datetime format '2018-02-27 00:02:47.952189+00:00'. Only ISO 8601 supported.
```
[df.zip](https://github.com/biolab/monroe-anal/files/1848005/df.zip)

**Comment by kernc** [comment]
```py
>>> from Orange.data import TimeVariable
>>> tvar = TimeVariable('date')
>>> tvar.parse('2018-02-27 00:02:47.952189+00:00')
---------------------------------------------------------------------------
ValueError: Invalid datetime format '2018-02-27 00:02:47.952189+00:00'. Only ISO 8601 supported.
```
Indeed, timezone specification in `'2018-02-27 00:02:47.952189+00:00'` is ISO-compliant, but apparently [Python's `stptime()` timezone specifier (`%z`)](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior) doesn't allow colons in timezone offsets.

This is an issue in [Orange's `TimeVariable`](https://github.com/biolab/orange3/blob/2833f193ec596a7aa3e60c3b731cdf92a3798504/Orange/data/variable.py#L863-L1054) datetime parsing. Please reraise the issue [here](https://github.com/biolab/orange3/issues).
